name: "✨ 기능 개발 (Feature)"
description: "새로운 기능 개발 요청"
labels: ["feat"]
body:
  - type: markdown
    attributes:
      value: |
        ## 이슈 제목 형식
        `feat(영역): 간결한 설명` (예: `feat(홈): 배너 자동 스크롤 추가`)

  - type: textarea
    id: description
    attributes:
      label: 작업 예정 내용
      description: 구현할 기능에 대해 상세히 설명해주세요.
      placeholder: |
        - 구현할 기능 1
        - 구현할 기능 2
    validations:
      required: true

  - type: textarea
    id: screen
    attributes:
      label: 화면 예시
      description: 디자인 시안이나 참고 화면이 있다면 첨부해주세요.
      placeholder: 이미지나 피그마 링크를 첨부해주세요.
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: 완료 조건
      description: 이 기능이 완료되었다고 판단할 수 있는 조건을 작성해주세요.
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 기타 참고사항이 있다면 작성해주세요.
    validations:
      required: false
